[package]
name = "cloak-share"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"
wgpu = "26.0.1"
pollster = "0.4.0"
screencapturekit = "0.3.6"
core-foundation = "0.10.1"
objc2 = "0.5"
core-video-sys = "0.1.4"
